version: "3"
services:
  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: jawimaDb
      MYSQL_USER: jawima
      MYSQL_PASSWORD: jawima
      MYSQL_ROOT_PASSWORD: jawima