version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgresJawima
    volumes:
      - "./.postgresql-data/db:/var/lib/postgresql"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=jawima
      - POSTGRES_USER=jawima
      - POSTGRES_DB=jawimaDb
    restart: unless-stopped